# Generated by Django 5.1 on 2024-09-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nysdapp', '0003_product_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='testimonials/')),
                ('testimonial', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
